### ISSUE TITLE
Fix connection to Certly's log server

### ISSUE THREAD

**Issue by tomfitzhenry** [certificate-transparency-watch/hs-certificate-transparency#34]
I can no longer connect to Certly's log server, because it only supports ECDSA, and Haskell's TLS library does not support ECDSA. See https://github.com/vincenthz/hs-tls/issues/120 for details.

Ping @iangcarroll

**Comment by iangcarroll** [comment]
I'll install an RSA certificate shortly.

**Comment by tomfitzhenry** [comment]
Thank you! And sorry for being in-part responsible for decreased security.

**Comment by tomfitzhenry** [comment]
https://github.com/vincenthz/hs-tls/issues/120 is supposedly fixed. I'll test whether I can connect to log.certly.io later.

**Comment by iangcarroll** [comment]
Ah, great. Let me know if you still need it to be swapped out.
